apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: your-app-psp
spec:
  privileged: false
  runAsUser:
    rule: 'MustRunAs'
    ranges:
    - min: 1000
      max: 1000
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  volumes:
  - '*'
