apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }} # Change this to your app's port
  livenessProbe:
    httpGet:
      path: {{ .Values.service.path }}
      port: {{ .Values.service.port }}
  readinessProbe:
    httpGet:
      path: {{ .Values.service.path }}
      port: {{ .Values.service.port }}
  