apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  ports:
  - port: 3000
    targetPort: 3000 # Change this to your app's port
  livenessProbe:
    httpGet:
      path: /
      port: 3000
  readinessProbe:
    httpGet:
      path: /
      port: 3000
  selector:
    app: node-app
  type: LoadBalancer # or NodePort if LoadBalancer is not available
  