# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Node Deployment CI/CD

on:
  push:
    branches:
      - master
      - test
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
      - test

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v2

    - name: Set DEPLOYED_FROM Environment Variable
      run: echo "DEPLOYED_FROM=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t ${DOCKER_USERNAME}/northladder_node_test:${{ github.sha }} .
        docker tag ${DOCKER_USERNAME}/northladder_node_test:${{ github.sha }} ${DOCKER_USERNAME}/northladder_node_test:latest

    - name: Log in to Docker Hub
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push ${DOCKER_USERNAME}/northladder_node_test

    - name: Deploy Application
      if: ${{ env.DEPLOYED_FROM != 'test' }}
      run: |
